version: 2
jobs:
  build:
    docker:
      - image: hseeberger/scala-sbt:11.0.3_1.2.8_2.13.0
    steps:
      - checkout
      - restore_cache:
          key: chess-resolver-{{ checksum "build.sbt" }}
      - run: sbt update
      - save_cache:
          paths:
            - ~/.ivy2
          key: chess-resolver-{{ checksum "build.sbt" }}
      - run: sbt coverage test coverageReport
      - run: bash <(curl -s https://codecov.io/bash)
